#!/usr/bin/env python3
"""Verify release ZIP identity, contents, and required entry points."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import zipfile


REQUIRED = {
    "bootstrap.py",
    "main.py",
    "Tumblr Scraper - Android.py",
    "Tumblr Scraper - Linux.desktop",
    "Tumblr Scraper - Windows.bat",
    "Tumblr Scraper - macOS.command",
    "Tumblr-Scraper-Linux.sh",
    "tumblr-scraper",
    "assets/archive.js",
    "assets/archive.css",
    "bridge/local_http.py",
    "network-policy.json",
    "context-policy.json",
    "RELEASE_GATE.md",
}
FORBIDDEN_PARTS = {
    "Backups",
    "Neighborhoods",
    ".git",
    ".runtime",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
}
EXECUTABLES = {
    "Tumblr Scraper - Linux.desktop",
    "Tumblr Scraper - macOS.command",
    "Tumblr-Scraper-Linux.sh",
    "tumblr-scraper",
}


def digest(path: Path) -> str:
    sha = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            sha.update(block)
    return sha.hexdigest()


def verify(zip_path: Path, manifest_path: Path | None = None, expected_commit: str | None = None) -> dict:
    if not zip_path.is_file():
        raise RuntimeError(f"ZIP does not exist: {zip_path}")
    with zipfile.ZipFile(zip_path) as archive:
        names = archive.namelist()
        if not names:
            raise RuntimeError("ZIP is empty")
        top_levels = {name.split("/", 1)[0] for name in names if name}
        if len(top_levels) != 1:
            raise RuntimeError(f"ZIP must contain one top-level directory: {sorted(top_levels)}")
        top = next(iter(top_levels))
        files = set()
        for name in names:
            parts = Path(name).parts
            if name.startswith("/") or ".." in parts:
                raise RuntimeError(f"Unsafe ZIP path: {name}")
            if any(part in FORBIDDEN_PARTS for part in parts):
                raise RuntimeError(f"Forbidden release content: {name}")
            if name.endswith("/"):
                continue
            if name.endswith((".pyc", ".pyo")):
                raise RuntimeError(f"Generated bytecode in release: {name}")
            relative = name.removeprefix(top + "/")
            if relative in EXECUTABLES:
                mode = (archive.getinfo(name).external_attr >> 16) & 0o777
                if not mode & 0o111:
                    raise RuntimeError(f"Executable permission missing from release: {name}")
            files.add(relative)
        missing = sorted(REQUIRED - files)
        if missing:
            raise RuntimeError(f"Required release files missing: {missing}")

    result = {
        "artifact": zip_path.name,
        "sha256": digest(zip_path),
        "size": zip_path.stat().st_size,
        "top_level": top,
    }
    if manifest_path:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        if manifest.get("artifact") != zip_path.name:
            raise RuntimeError("Manifest artifact name does not match ZIP")
        if manifest.get("sha256") != result["sha256"] or manifest.get("size") != result["size"]:
            raise RuntimeError("Manifest ZIP digest or size does not match")
        result["commit"] = manifest.get("commit")
    if expected_commit and result.get("commit") != expected_commit:
        raise RuntimeError("Release artifact was built from a different commit")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--zip", dest="zip_path", type=Path, required=True)
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--commit")
    args = parser.parse_args()
    print(json.dumps(verify(args.zip_path, args.manifest, args.commit), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
